;; disabling option touch as meta
(normal-erase-is-backspace-mode t)
(setq mac-option-key-is-meta nil)
(setq mac-option-modifier 'alt)
;;(setq mac-option-modifier nil)
(setq mac-function-modifier 'meta)
;;
(setq map (make-sparse-keymap))
(define-key key-translation-map [(alt \()] (kbd "{"))
(define-key key-translation-map [(alt \))] (kbd "}"))
(define-key key-translation-map (kbd "A-5") (kbd "["))
(define-key key-translation-map (kbd "A-°") (kbd "]"))
(define-key key-translation-map [(alt n)] (kbd "~"))
(define-key key-translation-map [(alt /)] (kbd "\\"))
(define-key key-translation-map [(alt shift l)] (kbd "|"))
